name: 'BlogOps'
description: 'Synchronize your github pages posts to your main blog platforms'
author: 'Andrea Grillo'
inputs: 
  posts-path:
    description: 'Path of the posts folder'
    default: './_posts/'
runs:
  using: 'docker'
  image: 'Dockerfile'
