name: 'BlogOps'
description: 'Synchronize your github pages posts to your main blog platforms'
author: 'Andrea Grillo'
inputs: 
  myInput:
    description: 'Input to use'
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'
