name: 'BlogOps'
description: 'Automate blogging'
author: 'Andrea Grillo'
branding:
  icon: 'upload'  
  color: 'green'
inputs:
  posts_dir:
    description: 'Path of the posts folder'
    required: false
    default: './_posts/'
  gh_access_token:
    description: 'Github token to read repository permission'
    required: true
  repo_name:
    description: 'Name of repository containing blog posts'
    required: true
  medium_integration_token:
    description: 'Token of personal Medium account'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
        architecture: x64
    - name: Install dependencies
      shell: bash
      working-directory: .
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run python script
      shell: bash
      working-directory: .
      run: python main.py
      env:
        INPUT_POSTS_DIR: ${{ inputs.posts_dir }}
        INPUT_REPO_NAME: ${{ inputs.repo_name }}
        INPUT_MEDIUM_INTEGRATION_TOKEN: ${{ inputs.medium_integration_token }}
        INPUT_GH_ACCESS_TOKEN: ${{ inputs.gh_access_token }}
