on: [push, pull_request]
jobs:
  run_composite_action:
    runs-on: ubuntu-latest
    steps:
      - name: Test action
        uses: ./.github/composite/
        id: action
        with:
          posts_dir: './tests/posts/'
          repo_name: "BlogOps"
          gh_access_token: ${{ secrets.GH_ACCESS_TOKEN }}
          medium_integration_token: ${{ secrets.MEDIUM_INTEGRATION_TOKEN }}
      - name: Get the action output
        run: echo "The action output is ${{ steps.action.outputs.myOutput }}" 
